"""Added changes in tenant and property

Revision ID: 80f9fad5ca14
Revises: ac8687fe6ccc
Create Date: 2025-04-15 11:39:15.960261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80f9fad5ca14'
down_revision: Union[str, None] = 'ac8687fe6ccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('landmark', sa.String(length=255), nullable=True))
    op.add_column('property', sa.Column('city', sa.String(length=255), nullable=True))
    op.add_column('property', sa.Column('state', sa.String(length=255), nullable=True))
    op.add_column('tenant', sa.Column('deposit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant', 'deposit')
    op.drop_column('property', 'state')
    op.drop_column('property', 'city')
    op.drop_column('property', 'landmark')
    # ### end Alembic commands ###
