"""Added changes in property models new total rooom 

Revision ID: a9bcdaf0f3b5
Revises: eda227cb236a
Create Date: 2025-04-13 15:01:30.209900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9bcdaf0f3b5'
down_revision: Union[str, None] = 'eda227cb236a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('total_rooms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property', 'total_rooms')
    # ### end Alembic commands ###
